### ISSUE TITLE
catch IndexError for empty dataframe

### ISSUE THREAD

**Issue by bsnacks000** [bsnacks000/binx#16]
* binx version: 0.2.3

An empty dataframe will throw an uncaught IndexError in utils. This should be handled with a Validation Error here 
```
Traceback (most recent call last):
  File "/home/bsnacks000/py_projects/bema/tests/test_post_models.py", line 110, in test_bad_data_raises_FactoryProcessorFailure
    post_models.create()
  File "/home/bsnacks000/py_projects/bema/bema/core/base.py", line 125, in create
    output = self._processor(**settings)  #NOTE returns serialized record list for the collection here
  File "/home/bsnacks000/py_projects/bema/bema/core/post_models.py", line 36, in _processor
    best_models_df = self.bestmodels_collection.to_dataframe()
  File "/home/bsnacks000/py_projects/bema/venv/lib/python3.5/site-packages/binx/collection.py", line 379, in to_dataframe
    return self._dataframe_with_dtypes(self.data)
  File "/home/bsnacks000/py_projects/bema/venv/lib/python3.5/site-packages/binx/collection.py", line 279, in _dataframe_with_dtypes
    col_data = rutil.records_to_columns(data)
  File "/home/bsnacks000/py_projects/bema/venv/lib/python3.5/site-packages/binx/utils.py", line 67, in records_to_columns
    return {k: [d[k] for d in records] for k in records[0]}
IndexError: list index out of range

```

**Comment by bsnacks000** [comment]
handled in dev branch for 0.3 release
