### ISSUE TITLE
numpy errors when allowing none

### ISSUE THREAD

**Issue by bsnacks000** [bsnacks000/binx#19]
* binx version: current
When casting objects to dataframes if a column allows none we must cast to an object dtype rather then an explicit numpy dtype. 

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

```
Traceback (most recent call last):
  File "/home/bsnacks000/py_projects/bema/tests/test_best_models.py", line 92, in test_processor_returns_expected_result_combined_elec_and_fuel
    good, rej = self.best_models.processor()
  File "/home/bsnacks000/py_projects/bema/bema/core/best_models.py", line 33, in processor
    baseline_stats_df = self.baseline_collection.to_dataframe()
  File "/home/bsnacks000/py_projects/bema/venv/lib/python3.5/site-packages/binx/collection.py", line 379, in to_dataframe
    return self._dataframe_with_dtypes(self.data)
  File "/home/bsnacks000/py_projects/bema/venv/lib/python3.5/site-packages/binx/collection.py", line 286, in _dataframe_with_dtypes
    df_data[col] = pd.Series(col_data[col], dtype=dtype)
  File "/home/bsnacks000/py_projects/bema/venv/lib/python3.5/site-packages/pandas/core/series.py", line 275, in __init__
    raise_cast_failure=True)
  File "/home/bsnacks000/py_projects/bema/venv/lib/python3.5/site-packages/pandas/core/series.py", line 4114, in _sanitize_array
    subarr = _try_cast(data, False)
  File "/home/bsnacks000/py_projects/bema/venv/lib/python3.5/site-packages/pandas/core/series.py", line 4053, in _try_cast
    copy=copy)
  File "/home/bsnacks000/py_projects/bema/venv/lib/python3.5/site-packages/pandas/core/dtypes/cast.py", line 1257, in construct_1d_ndarray_preserving_na
    subarr = np.array(values, dtype=dtype, copy=copy)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

```

**Comment by bsnacks000** [comment]
Closing this... current 0.3.dev branch did not throw this error
