### ISSUE TITLE
non-required date fields throw key-error 

### ISSUE THREAD

**Issue by bsnacks000** [bsnacks000/binx#7]
* binx version: 0.2.1

If a non-required Datetime or Date field is instrospected during serialization, a key error is thrown since its looking for column that does not exist. This happens when loading a test-fixture....

Probably just need to add an additional check to see whether the field is required or not if its not present in the loaded data 

```
======================================================================
ERROR: test_bema_utility_instantiates_with_fixtures (tests.test_collections.TestCollections)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bsnacks000/py_projects/utility/bpl-utility/tests/test_collections.py", line 69, in test_bema_utility_instantiates_with_fixtures
    u.load_data(test)
  File "/home/bsnacks000/py_projects/utility/venv-util/lib/python3.5/site-packages/binx/collection.py", line 342, in load_data
    raise CollectionLoadError('An error occurred while loading and validating records') from err
binx.exceptions.CollectionLoadError: An error occurred while loading and validating records
-------------------- >> begin captured logging << --------------------
faker.factory: DEBUG: Not in REPL -> leaving logger event level as is.
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_monthly_utility_instantiates_with_fixtures (tests.test_collections.TestCollections)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bsnacks000/py_projects/utility/venv-util/lib/python3.5/site-packages/binx/collection.py", line 326, in load_data
    records = self._clean_records(records)
  File "/home/bsnacks000/py_projects/utility/venv-util/lib/python3.5/site-packages/binx/collection.py", line 313, in _clean_records
    records = util.date_to_string(formatfields, records)
  File "/home/bsnacks000/py_projects/utility/venv-util/lib/python3.5/site-packages/binx/utils.py", line 81, in date_to_string
    if isinstance(rec[col], datetime.datetime):
KeyError: 'start_date'

```

**Comment by bsnacks000** [comment]
handled in #9
