### ISSUE TITLE
KeyError in to_dataframe() for non-required fields 

### ISSUE THREAD

**Issue by bsnacks000** [bsnacks000/binx#8]
* binx version: 0.2.1

to_dataframe() should swallow key-errors or check for non-required fields 
```
Traceback (most recent call last):
  File "/home/bsnacks000/py_projects/utility/bpl-utility/tests/test_adapters.py", line 211, in test_adapt_returns_expected_result
    self.assertListEqual(result.collection.to_dataframe()['OAT'].tolist(), [30.0, 35.0, 40.0, 45.0])
  File "/home/bsnacks000/py_projects/utility/venv-util/lib/python3.5/site-packages/binx/collection.py", line 375, in to_dataframe
    return self._dataframe_with_dtypes(self.data)
  File "/home/bsnacks000/py_projects/utility/venv-util/lib/python3.5/site-packages/binx/collection.py", line 285, in _dataframe_with_dtypes
    df_data[col] = pd.Series(col_data[col], dtype=dtype)
KeyError: 'temp_max'

```

**Comment by bsnacks000** [comment]
handled in #9
